[tool.poetry]
name = "ai-study-buddy"
version = "0.1.0"
description = ""
authors = ["Edgar454 <mevaed4@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
